# Generated by Django 3.2.6 on 2021-10-19 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0012_auto_20211017_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 19, 21, 10, 1, 6146), verbose_name='Registratsiya sanasi:'),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 10, 19, 21, 10, 1, 6146), verbose_name="Vaqtga ko'ra:")),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.lessons')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academy.academyusers')),
            ],
            options={
                'verbose_name': "O'quvchi bahosi",
                'verbose_name_plural': "O'quvchilar baholari",
            },
        ),
    ]
