# Generated by Django 3.2.6 on 2021-10-23 10:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0013_auto_20211019_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 23, 15, 29, 19, 62128), verbose_name='Registratsiya sanasi:'),
        ),
    ]
